export const PARKS_LOADING = 'PARKS_LOADING';
export const STOP_PARKS_LOADING = 'STOP_PARKS_LOADING';
export const PARK_LOADING = 'PARK_LOADING';
export const STOP_PARK_LOADING = 'STOP_PARK_LOADING';
export const DAY_LOADING = 'DAY_LOADING';
export const STOP_DAY_LOADING = 'STOP_DAY_LOADING';
export const MAKE_RESERVATION_LOADING = 'MAKE_RESERVATION_LOADING';
export const STOP_MAKE_RESERVATION_LOADING = 'STOP_MAKE_RESERVATION_LOADING';